"""Interactive first-run setup: ``virtual-flex setup``.

Writes ``/etc/virtual-flex/config.toml`` from a few prompts so the user never
edits TOML by hand. Auto-detects the LAN broadcast, resolves the K4 by serial
over mDNS (or takes an IP), pins the derived Flex serial so it can't drift, and
offers to enable + start the service.

Only the user's meaningful choices are written; everything else (ports, poll
intervals, presence debounce) falls back to the built-in defaults, so future
default improvements apply without re-running setup.
"""
from __future__ import annotations

import asyncio
import os
import re
import subprocess
import sys
import tomllib
from pathlib import Path

from . import mdns
from .config import derive_flex_serial, detect_local_ip

CONFIG_PATH = "/etc/virtual-flex/config.toml"
_MODEL = "FLEX-8600"
_VERSION = "4.2.20.41343"


def load_existing(path: Path) -> dict:
    """Previous config, if any — re-running setup pre-fills prompts from it, so
    changing one setting (e.g. adding unicast targets) doesn't mean retyping
    everything."""
    try:
        with open(path, "rb") as f:
            return tomllib.load(f)
    except (OSError, ValueError):
        return {}


def k4_serial_from_hostname(hostname: str) -> str:
    """'K4-SN01234.local' -> '01234' (the wizard's first prompt's default)."""
    m = re.match(r"K4-SN(.+?)\.local$", hostname.strip(), re.IGNORECASE)
    return m.group(1) if m else ""


def normalize_k4_serial(serial: str) -> str:
    """The K4's hostname zero-pads the serial to 5 digits (K4-SN01234), so
    '1234' must become '01234' or the mDNS name won't exist."""
    s = serial.strip()
    return s.zfill(5) if s.isdigit() and len(s) < 5 else s


async def scan_for_k4s(local_ip: str, *, port: int = 9200,
                       connect_timeout: float = 0.6,
                       hosts: list[str] | None = None) -> list[tuple[str, str]]:
    """Probe the local /24 for radios: any host with the CAT port open is asked
    for its serial over CAT (``SN;`` -> ``SNnnnnn;``). Returns [(ip, serial)];
    serial is '' for a listener that didn't answer the query."""
    base = local_ip.rsplit(".", 1)[0]

    async def probe(ip: str) -> tuple[str, str] | None:
        try:
            reader, writer = await asyncio.wait_for(
                asyncio.open_connection(ip, port), connect_timeout)
        except (OSError, asyncio.TimeoutError):
            return None
        serial = ""
        try:
            writer.write(b"SN;")
            await writer.drain()
            data = await asyncio.wait_for(reader.read(64), 1.5)
            m = re.search(rb"SN(\d+)", data)
            if m:
                serial = m.group(1).decode().zfill(5)
        except (OSError, asyncio.TimeoutError):
            pass
        finally:
            writer.close()
        return (ip, serial)

    if hosts is None:
        hosts = [f"{base}.{i}" for i in range(1, 255)]
    hits = await asyncio.gather(*(probe(ip) for ip in hosts))
    return [h for h in hits if h]


def subnet_broadcast(ip: str) -> str:
    """Best-effort /24 subnet-directed broadcast for an IPv4 (192.0.2.14 ->
    10.0.1.255). The user can override at the prompt for other prefix lengths."""
    parts = ip.split(".")
    if len(parts) == 4 and all(p.isdigit() for p in parts):
        return ".".join(parts[:3] + ["255"])
    return "255.255.255.255"


def build_config(*, k4_ip: str, k4_hostname: str, serial: str, callsign: str,
                 nickname: str, broadcast: str,
                 discovery_targets: list[str] | None = None) -> str:
    """Render a minimal config.toml. Omitted keys (ports, intervals, presence)
    inherit config.py defaults."""
    targets_line = ""
    if discovery_targets:
        quoted = ", ".join(f'"{t}"' for t in discovery_targets)
        targets_line = (f"discovery_targets = [{quoted}]   "
                        "# unicast-only: invisible to other pickers\n")
    return (
        "# Generated by `virtual-flex setup`. Re-run it any time to change these.\n"
        "[radio]\n"
        f'model    = "{_MODEL}"\n'
        f'serial   = "{serial}"       # pinned, so a K4 rename can never force a stack re-pair\n'
        f'version  = "{_VERSION}"\n'
        f'nickname = "{nickname}"\n'
        f'callsign = "{callsign}"\n'
        "\n"
        "[network]\n"
        f'broadcast_address = "{broadcast}"\n'
        f"{targets_line}"
        'advertise_ip      = ""\n'
        "\n"
        "[k4]\n"
        f'ip       = "{k4_ip}"\n'
        f'hostname = "{k4_hostname}"   # for mDNS IP self-heal if the address changes\n'
    )


def _prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        val = input(f"{label}{suffix}: ").strip()
    except EOFError:
        val = ""
    return val or default


def _yes(label: str, default_no: bool = True) -> bool:
    d = "y/N" if default_no else "Y/n"
    ans = _prompt(f"{label} ({d})", "").lower()
    if not ans:
        return not default_no
    return ans.startswith("y")


async def _resolve(hostname: str) -> str | None:
    try:
        return await mdns.resolve(hostname, timeout=3.0)
    except OSError:
        return None


def run(argv: list[str] | None = None) -> int:
    print("=== virtual-flex setup ===\n")
    local_ip = detect_local_ip()
    path = Path(os.environ.get("VIRTUALFLEX_CONFIG", CONFIG_PATH))
    existing = load_existing(path)
    ex_radio = existing.get("radio", {})
    ex_net = existing.get("network", {})
    ex_k4 = existing.get("k4", {})
    if existing:
        print(f"(pre-filled from {path} — Enter keeps the current value)\n")

    # --- locate the K4 ---
    serial_in = _prompt("K4 serial (the digits in K4-SN..., blank to scan the network)",
                        k4_serial_from_hostname(str(ex_k4.get("hostname", ""))))
    serial_in = normalize_k4_serial(serial_in)
    k4_hostname = k4_ip = ""
    if serial_in:
        k4_hostname = f"K4-SN{serial_in}.local"
        print(f"  resolving {k4_hostname} over mDNS ...")
        k4_ip = asyncio.run(_resolve(k4_hostname)) or ""
        if k4_ip:
            print(f"  found the K4 at {k4_ip}")
        else:
            print("  no mDNS answer (K4 off, or on another subnet)")
    if not k4_ip:
        print(f"  scanning {local_ip.rsplit('.', 1)[0]}.0/24 for radios (CAT port open) ...")
        found = asyncio.run(scan_for_k4s(local_ip))
        for ip, sn in found:
            print(f"  found a radio at {ip}" + (f" (serial {sn})" if sn else ""))
        if len(found) == 1:
            k4_ip, sn = found[0]
            if sn and not serial_in:
                serial_in = sn
            k4_hostname = k4_hostname or (f"K4-SN{sn}.local" if sn else "")
            if not _yes(f"Use the K4 at {k4_ip}?", default_no=False):
                k4_ip = ""
        elif found:
            pick = _prompt("  which IP?", found[0][0])
            match = next(((ip, sn) for ip, sn in found if ip == pick), None)
            if match:
                k4_ip = match[0]
                if match[1]:
                    k4_hostname = k4_hostname or f"K4-SN{match[1]}.local"
        else:
            print("  no radios answered (K4 off?)")
    if not k4_ip:
        k4_ip = _prompt("K4 IP address", str(ex_k4.get("ip", "")))
        k4_hostname = k4_hostname or _prompt(
            "K4 hostname for IP self-heal (optional, e.g. K4-SN01234.local)",
            str(ex_k4.get("hostname", "")))
    if not k4_ip and not k4_hostname:
        print("\nNeed at least a K4 IP or hostname — nothing written.")
        return 1

    # --- identity + network ---
    derived = derive_flex_serial(_MODEL, k4_hostname) if k4_hostname else None
    serial = _prompt("Flex serial to advertise (pinned)",
                     str(ex_radio.get("serial", "")) or derived or "0000-0000-0000-0000")
    callsign = _prompt("Your callsign", str(ex_radio.get("callsign", "")))
    nickname = _prompt("Radio nickname shown in the apps",
                       str(ex_radio.get("nickname", "")) or "VirtualFlex")
    broadcast = _prompt("LAN broadcast address",
                        str(ex_net.get("broadcast_address", "")) or subnet_broadcast(local_ip))
    print("\nDiscovery: broadcast reaches every picker on the LAN (SmartSDR/Maestro"
          "\nwill list this virtual radio). Unicast sends ONLY to your Genius boxes"
          "\n- invisible to everything else. Pair the boxes in broadcast mode first.")
    targets_default = ", ".join(str(t) for t in ex_net.get("discovery_targets", []) or [])
    targets_in = _prompt("Genius box IPs for unicast (comma-separated; blank = broadcast; "
                         "'none' clears)", targets_default)
    if targets_in.strip().lower() in ("none", "broadcast"):
        targets_in = ""
    discovery_targets = [t.strip() for t in targets_in.split(",") if t.strip()]

    cfg = build_config(k4_ip=k4_ip, k4_hostname=k4_hostname, serial=serial,
                       callsign=callsign, nickname=nickname, broadcast=broadcast,
                       discovery_targets=discovery_targets)
    print(f"\n--- {path} ---\n{cfg}")
    if not _yes("Write this config?", default_no=False):
        print("Aborted; nothing written.")
        return 1
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(cfg)
    except PermissionError:
        print(f"\nPermission denied writing {path}. Re-run with sudo.")
        return 1
    print(f"Wrote {path}.")

    if _yes("Enable and start virtual-flex now?", default_no=False):
        subprocess.run(["systemctl", "daemon-reload"], check=False)
        subprocess.run(["systemctl", "enable", "--now", "virtual-flex.service"], check=False)
        print("Started. Watch it:  journalctl -u virtual-flex -f")
    else:
        print("Later:  sudo systemctl enable --now virtual-flex")
    print(f"\nPair the 4O3A stack to serial:  {serial}")
    return 0
