"""Interactive first-run setup: ``virtual-flex setup``.

Writes ``/etc/virtual-flex/config.toml`` from a few prompts so the user never
edits TOML by hand. Auto-detects the LAN broadcast, resolves the K4 by serial
over mDNS (or takes an IP), pins the derived Flex serial so it can't drift, and
offers to enable + start the service.

Only the user's meaningful choices are written; everything else (ports, poll
intervals, presence debounce) falls back to the built-in defaults, so future
default improvements apply without re-running setup.
"""
from __future__ import annotations

import asyncio
import os
import subprocess
import sys
from pathlib import Path

from . import mdns
from .config import derive_flex_serial, detect_local_ip

CONFIG_PATH = "/etc/virtual-flex/config.toml"
_MODEL = "FLEX-8600"
_VERSION = "3.6.19.35"


def subnet_broadcast(ip: str) -> str:
    """Best-effort /24 subnet-directed broadcast for an IPv4 (10.0.1.14 ->
    10.0.1.255). The user can override at the prompt for other prefix lengths."""
    parts = ip.split(".")
    if len(parts) == 4 and all(p.isdigit() for p in parts):
        return ".".join(parts[:3] + ["255"])
    return "255.255.255.255"


def build_config(*, k4_ip: str, k4_hostname: str, serial: str, callsign: str,
                 nickname: str, broadcast: str) -> str:
    """Render a minimal config.toml. Omitted keys (ports, intervals, presence)
    inherit config.py defaults."""
    return (
        "# Generated by `virtual-flex setup`. Re-run it any time to change these.\n"
        "[radio]\n"
        f'model    = "{_MODEL}"\n'
        f'serial   = "{serial}"       # pinned, so a K4 rename can never force a stack re-pair\n'
        f'version  = "{_VERSION}"\n'
        f'nickname = "{nickname}"\n'
        f'callsign = "{callsign}"\n'
        "\n"
        "[network]\n"
        f'broadcast_address = "{broadcast}"\n'
        'advertise_ip      = ""\n'
        "\n"
        "[k4]\n"
        f'ip       = "{k4_ip}"\n'
        f'hostname = "{k4_hostname}"   # for mDNS IP self-heal if the address changes\n'
    )


def _prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        val = input(f"{label}{suffix}: ").strip()
    except EOFError:
        val = ""
    return val or default


def _yes(label: str, default_no: bool = True) -> bool:
    d = "y/N" if default_no else "Y/n"
    ans = _prompt(f"{label} ({d})", "").lower()
    if not ans:
        return not default_no
    return ans.startswith("y")


async def _resolve(hostname: str) -> str | None:
    try:
        return await mdns.resolve(hostname, timeout=3.0)
    except OSError:
        return None


def run(argv: list[str] | None = None) -> int:
    print("=== virtual-flex setup ===\n")
    local_ip = detect_local_ip()

    # --- locate the K4 ---
    serial_in = _prompt("K4 serial (the digits in K4-SN..., blank to enter an IP instead)")
    k4_hostname = k4_ip = ""
    if serial_in:
        k4_hostname = f"K4-SN{serial_in}.local"
        print(f"  resolving {k4_hostname} over mDNS ...")
        k4_ip = asyncio.run(_resolve(k4_hostname)) or ""
        if k4_ip:
            print(f"  found the K4 at {k4_ip}")
        else:
            print("  no mDNS answer (K4 off, or on another subnet)")
            k4_ip = _prompt("  K4 IP address")
    else:
        k4_ip = _prompt("K4 IP address")
        k4_hostname = _prompt("K4 hostname for IP self-heal (optional, e.g. K4-SN00895.local)")
    if not k4_ip and not k4_hostname:
        print("\nNeed at least a K4 IP or hostname — nothing written.")
        return 1

    # --- identity + network ---
    derived = derive_flex_serial(_MODEL, k4_hostname) if k4_hostname else None
    serial = _prompt("Flex serial to advertise (pinned)", derived or "0000-0000-0000-0000")
    callsign = _prompt("Your callsign")
    nickname = _prompt("Radio nickname shown in the apps", "VirtualFlex")
    broadcast = _prompt("LAN broadcast address", subnet_broadcast(local_ip))

    cfg = build_config(k4_ip=k4_ip, k4_hostname=k4_hostname, serial=serial,
                       callsign=callsign, nickname=nickname, broadcast=broadcast)

    path = Path(os.environ.get("VIRTUALFLEX_CONFIG", CONFIG_PATH))
    print(f"\n--- {path} ---\n{cfg}")
    if not _yes("Write this config?", default_no=False):
        print("Aborted; nothing written.")
        return 1
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(cfg)
    except PermissionError:
        print(f"\nPermission denied writing {path}. Re-run with sudo.")
        return 1
    print(f"Wrote {path}.")

    if _yes("Enable and start virtual-flex now?", default_no=False):
        subprocess.run(["systemctl", "daemon-reload"], check=False)
        subprocess.run(["systemctl", "enable", "--now", "virtual-flex.service"], check=False)
        print("Started. Watch it:  journalctl -u virtual-flex -f")
    else:
        print("Later:  sudo systemctl enable --now virtual-flex")
    print(f"\nPair the 4O3A stack to serial:  {serial}")
    return 0
