#!/usr/bin/env bash
#
# build-deb.sh — build the virtual-flex .deb (architecture: all, pure Python).
# Usage: bash deploy/build-deb.sh [version]   (version defaults to pyproject)
# Needs dpkg-deb (Debian/Ubuntu, or `apt install dpkg`). Output: dist/*.deb
#
# v0.2: native K4, no hamlib. One service, no rigctld unit, no libhamlib dep.
# The config is generated by `virtual-flex setup`, not shipped as a conffile.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PKG_DIR="${REPO_DIR}/deploy/pkg"
VERSION="${1:-$(sed -nE 's/^version *= *"([^"]+)".*/\1/p' "${REPO_DIR}/pyproject.toml" | head -1)}"
[ -n "$VERSION" ] || { echo "could not determine version"; exit 1; }

# __version__ must match: the self-updater compares GitHub tags against it,
# and a stale constant makes `virtual-flex update` reinstall forever.
PKG_VERSION="$(sed -nE 's/^__version__ *= *"([^"]+)".*/\1/p' "${REPO_DIR}/virtualflex/__init__.py" | head -1)"
[ "$PKG_VERSION" = "$VERSION" ] || {
  echo "version mismatch: pyproject=$VERSION but virtualflex/__init__.py=$PKG_VERSION"; exit 1; }
PKG=virtual-flex
ARCH=all

command -v dpkg-deb >/dev/null || { echo "dpkg-deb not found (apt install dpkg)"; exit 1; }

STAGE="$(mktemp -d)/${PKG}_${VERSION}_${ARCH}"
mkdir -p "$STAGE/DEBIAN" "$STAGE/usr/lib/virtual-flex" "$STAGE/lib/systemd/system" \
         "$STAGE/usr/bin" "$STAGE/usr/share/doc/virtual-flex"

# --- payload ---
cp -r "${REPO_DIR}/virtualflex" "$STAGE/usr/lib/virtual-flex/"
find "$STAGE/usr/lib/virtual-flex" -name '__pycache__' -type d -prune -exec rm -rf {} +
cp "${PKG_DIR}/virtual-flex.service" "$STAGE/lib/systemd/system/"
cp "${REPO_DIR}/config.example.toml" "$STAGE/usr/share/doc/virtual-flex/"
cp "${REPO_DIR}/README.md" "$STAGE/usr/share/doc/virtual-flex/"

# --- /usr/bin/virtual-flex wrapper (so `virtual-flex setup` etc. work on PATH) ---
cat > "$STAGE/usr/bin/virtual-flex" <<'EOF'
#!/bin/sh
export PYTHONPATH=/usr/lib/virtual-flex${PYTHONPATH:+:$PYTHONPATH}
exec python3 -m virtualflex "$@"
EOF
chmod 0755 "$STAGE/usr/bin/virtual-flex"

# --- control metadata ---
INSTALLED_KB="$(du -sk "$STAGE" | cut -f1)"
cat > "$STAGE/DEBIAN/control" <<EOF
Package: ${PKG}
Version: ${VERSION}
Section: hamradio
Priority: optional
Architecture: ${ARCH}
Depends: python3 (>= 3.11)
Maintainer: AB0R <gsa700@users.noreply.github.com>
Homepage: https://github.com/gsa700/virtual-flex
Installed-Size: ${INSTALLED_KB}
Description: Virtual FlexRadio for the 4O3A Genius stack (native K4)
 Impersonates a FLEX-8600 on the LAN so an Elecraft K4/K4D drives the 4O3A
 PGXL/TGXL/AGXL stack over the network - band-follow and keying - with no
 hamlib. A presence supervisor drops the stack (so each box reverts to its
 no-transceiver antenna) when the K4 is off, like a real Flex powering down.
 Configure with: sudo virtual-flex setup
EOF

# No conffiles: /etc/virtual-flex/config.toml is generated by `virtual-flex setup`,
# so dpkg never prompts about it on upgrade and never clobbers the user's config.

cat > "$STAGE/DEBIAN/postinst" <<'EOF'
#!/bin/sh
set -e
systemctl daemon-reload || true
echo ""
echo "virtual-flex installed.  Configure it (no file editing needed):"
echo "    sudo virtual-flex setup"
echo "That resolves your K4, writes /etc/virtual-flex/config.toml, and can"
echo "enable + start the service. The host must share the 4O3A stack's subnet."
exit 0
EOF

cat > "$STAGE/DEBIAN/prerm" <<'EOF'
#!/bin/sh
set -e
if [ "$1" = remove ] || [ "$1" = purge ]; then
  systemctl stop virtual-flex.service >/dev/null 2>&1 || true
  systemctl disable virtual-flex.service >/dev/null 2>&1 || true
fi
exit 0
EOF

cat > "$STAGE/DEBIAN/postrm" <<'EOF'
#!/bin/sh
set -e
systemctl daemon-reload >/dev/null 2>&1 || true
if [ "$1" = remove ] || [ "$1" = purge ]; then
  # Runtime-generated __pycache__ isn't in the package manifest, so dpkg
  # leaves it behind and the install dir gets orphaned — sweep it ourselves.
  rm -rf /usr/lib/virtual-flex
fi
if [ "$1" = purge ]; then
  rm -rf /etc/virtual-flex
fi
exit 0
EOF

chmod 0755 "$STAGE/DEBIAN/postinst" "$STAGE/DEBIAN/prerm" "$STAGE/DEBIAN/postrm"

mkdir -p "${REPO_DIR}/dist"
OUT="${REPO_DIR}/dist/${PKG}_${VERSION}_${ARCH}.deb"
dpkg-deb --build --root-owner-group "$STAGE" "$OUT"
echo "built: $OUT"
