#!/usr/bin/env bash
#
# install.sh — set up virtual-flex as always-on systemd services.
#
# Target: any Debian 12+ / Ubuntu 22.04+ host (VM, LXC, or Raspberry Pi) that is
# on the SAME subnet/VLAN as the 4O3A stack — discovery is a UDP broadcast, so
# the host must share the stack's L2 segment. It reaches the K4 and the stack
# entirely over the LAN; no wires, no serial.
#
# Run from INSIDE the cloned repo, with sudo:
#     sudo bash deploy/install.sh
#
# Override any default with an env var (use `sudo -E` so they pass through).
# Set K4_IP to your K4's network-CAT address; a subnet-directed broadcast is
# safest. Optionally set RUN_USER to the account the services run as.
#     K4_IP=192.168.1.105 BROADCAST_ADDR=192.168.1.255 RUN_USER=svc sudo -E bash deploy/install.sh
#
# Requires Python 3.11+ (Debian 12 Bookworm / 13 Trixie both qualify).

set -euo pipefail

# ---- settings (override via env) -------------------------------------------
K4_IP="${K4_IP:-192.168.1.100}"                     # K4 network-CAT IP  (override for your station)
K4_CAT_PORT="${K4_CAT_PORT:-9200}"                  # K4 CAT port
RIG_MODEL="${RIG_MODEL:-2047}"                      # hamlib model (2047 = Elecraft K4)
RIGCTLD_PORT="${RIGCTLD_PORT:-4532}"                # local rigctld port
FLEX_SERIAL="${FLEX_SERIAL:-1234-5678-9012-3456}"   # serial the 4O3A stack pairs to
BROADCAST_ADDR="${BROADCAST_ADDR:-255.255.255.255}" # subnet bcast is safest, e.g. 192.168.1.255
CALLSIGN="${CALLSIGN:-AB0R}"
NICKNAME="${NICKNAME:-VirtualFlex}"

# ---- helpers / derived paths -----------------------------------------------
log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run with sudo:  sudo bash deploy/install.sh"

# Account the services run as. Defaults to the sudo caller; override with RUN_USER=.
RUN_USER="${RUN_USER:-${SUDO_USER:-$(id -un)}}"
[ "$RUN_USER" = "root" ] && warn "services will run as root — set RUN_USER=<account> for a non-root user"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
[ -d "${REPO_DIR}/virtualflex" ] || die "virtualflex/ not found — run this from inside the cloned repo."

# ---- 1. packages -----------------------------------------------------------
log "Installing hamlib + git"
apt-get update -qq
apt-get install -y -qq libhamlib-utils git

# ---- 2. preflight checks ---------------------------------------------------
PY="$(command -v python3 || true)"
[ -n "$PY" ] || die "python3 not found"
"$PY" - <<'EOF' || die "Python 3.11+ required (tomllib) — use Raspberry Pi OS Bookworm or newer."
import sys; sys.exit(0 if sys.version_info[:2] >= (3, 11) else 1)
EOF
log "$("$PY" --version) OK"

RIGCTLD="$(command -v rigctld)" || die "rigctld not found after install"
if rigctl -l | grep -qiE "(^|[[:space:]])${RIG_MODEL}[[:space:]].*K4|[[:space:]]K4[[:space:]]"; then
  log "hamlib K4 backend (model ${RIG_MODEL}) present"
else
  warn "Model ${RIG_MODEL}/K4 not found in 'rigctl -l' — your hamlib may be too old; the service could fail."
fi

# ---- 3. config.toml --------------------------------------------------------
CFG="${REPO_DIR}/config.toml"
if [ -e "$CFG" ]; then
  warn "config.toml already exists — leaving it untouched"
else
  log "Writing ${CFG}"
  cat > "$CFG" <<EOF
# Generated by deploy/install.sh
[radio]
model    = "FLEX-8600"
serial   = "${FLEX_SERIAL}"
version  = "3.6.19.35"
name     = "${NICKNAME}"
nickname = "${NICKNAME}"
callsign = "${CALLSIGN}"

[network]
command_port       = 4992
discovery_port     = 4992
broadcast_address  = "${BROADCAST_ADDR}"
discovery_interval = 1.0
advertise_ip       = ""

[rig]
source = "hamlib"

[rig.hamlib]
host          = "127.0.0.1"
port          = ${RIGCTLD_PORT}
poll_interval = 0.1

[ptt]
source = "k4cat"

[ptt.k4cat]
host          = "${K4_IP}"
port          = ${K4_CAT_PORT}
poll_interval = 0.003
EOF
  chown "${RUN_USER}:${RUN_USER}" "$CFG"
fi

# ---- 4. systemd units ------------------------------------------------------
log "Installing systemd services (user=${RUN_USER}, dir=${REPO_DIR})"
cat > /etc/systemd/system/rigctld.service <<EOF
[Unit]
Description=Hamlib rigctld for K4 (virtual-flex)
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=${RIGCTLD} -m ${RIG_MODEL} -r ${K4_IP}:${K4_CAT_PORT} -t ${RIGCTLD_PORT}
Restart=always
RestartSec=5
User=${RUN_USER}

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/virtual-flex.service <<EOF
[Unit]
Description=virtual-flex (FlexRadio emulator for the 4O3A stack)
After=rigctld.service network-online.target
Wants=rigctld.service

[Service]
WorkingDirectory=${REPO_DIR}
ExecStart=${PY} -m virtualflex --config config.toml --log-level INFO
Restart=always
RestartSec=5
User=${RUN_USER}

[Install]
WantedBy=multi-user.target
EOF

# ---- 5. enable + start -----------------------------------------------------
log "Enabling and starting services"
systemctl daemon-reload
systemctl enable --now rigctld.service virtual-flex.service

log "Done."
echo
systemctl --no-pager --lines=0 status rigctld.service virtual-flex.service || true
cat <<EOF

virtual-flex is running as a service.
  Pair the 4O3A stack to serial:  ${FLEX_SERIAL}
  Watch logs:                     journalctl -u virtual-flex -f
  Restart after code changes:     sudo systemctl restart virtual-flex
  Stop:                           sudo systemctl stop virtual-flex rigctld
EOF
